server:
  port: 9094

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notificationdb
    username: jodos
    password: jodos2006
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    username: admin
    password: admin123
    host: localhost
    port: 5672
    template:
      mandatory: true
      receive-timeout: 50000
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-retries: 3
          multiplier: 2
        acknowledge-mode: auto
  mail:
    host : smtp.gmail.com
    port : 587
    username : jodos2006@gmail.com
    password : uizm uwcm gcts rcub
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    test-connection: false
# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.seatwise: DEBUG
    org.springframework.amqp: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${server.port}
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 45

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
