server:
  port: 9093

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notificationdb
    username: jodos
    password: jodos2006
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.springframework: INFO
