spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
server:
  port: 8761
  ssl:
    enabled: false
    key-store: classpath:eureka-server.p12
    key-store-password: 200696
    key-store-type: PKCS12
    key-alias: eureka-server
  servlet:
    context-path: /dashboard
management:
  endpoints:
    web:
      exposure:
        exclude: "*"
  endpoint:
    health:
      show-details: always